workflows:
  ios-sideload-build:
    name: iOS Sideloadly Build
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Paketleri Indir
        script: |
          cd ilac_dostu
          flutter pub get
      - name: Imzasiz iOS Derle (Gercek Cihaz Icin)
        script: |
          cd ilac_dostu
          flutter build ios --release --no-codesign
      - name: Sideloadly Icin IPA Olustur
        script: |
          cd ilac_dostu/build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -q -r app.ipa Payload
    artifacts:
      - ilac_dostu/build/ios/iphoneos/app.ipa
